vich_uploader:
  db_driver: orm

  mappings:
    document_object:
      uri_prefix: /document
      upload_destination: '%kernel.project_dir%/public/documents'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      directory_namer: vich_uploader.directory_namer_subdir

